version: 2.1

executors:
  common-env:
    working_directory: ~/repo/maybe

    docker:
      - image: circleci/openjdk:13-jdk-buster
        environment:
          JVM_OPTS: -Xmx4096m
          TERM: dumb

commands:
  setup-env:
    description: "Setup the common environment to run tasks on CI"

    steps:
      - checkout:
          path: ~/repo/maybe

      - run:
          name: Generate gradle.lock
          command: |
            cat gradle/wrapper/gradle-wrapper.properties gradle/dependency-locks/* > gradle.lock
            echo "All lock files were merged into gradle.lock file"

      - run:
          name: Provide Credentials
          command: |
            cp gradle.properties.sample gradle.properties
            sed -i "s/<SIGNING_PASSWORD>/$SIGNING_PASSWORD/g" gradle.properties
            sed -i "s/<OSSRH_PASSWORD>/$OSSRH_PASSWORD/g" gradle.properties
            echo "All credentials were provisioned to gradle.properties file"

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "gradle.lock" }}
            - v1-dependencies-

jobs:
  build:
    executor: common-env

    steps:
      - setup-env

      - run:
          name: Setup Code Climate
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: Lint Gradle
          command: ./gradlew lintGradle

      - run:
          name: Compile and build
          command: ./gradlew build -x test

      - run:
          name: Test
          command: |
            ./cc-test-reporter before-build 
            ./gradlew test

      - run:
          name: Coverage
          command: ./gradlew jacocoTestReport

      - save_cache:
          paths:
            - ~/repo/maybe/.gradle
            - ~/.gradle
          key: v1-dependencies-{{ checksum "gradle.lock" }}

      - deploy:
          name: Upload reports
          command: bash <(curl -s https://codecov.io/bash)

      - deploy:
          name: Code Climate reports
          command: |
            ./cc-test-reporter format-coverage --input-type jacoco build/reports/jacoco/test/jacocoTestReport.xml
            ./cc-test-reporter upload-coverage
          environment:
            JACOCO_SOURCE_PATH: src/main/java

      - store_test_results:
          path: build/test-results

  publish-snapshot:
    executor: common-env

    steps:
      - setup-env

      - deploy:
          name: Publish to Sonatype Snapshot OSSRH
          command: ./gradlew publish

  publish-release:
    executor: common-env

    steps:
      - setup-env

      - deploy:
          name: Upload to Sonatype Release OSSRH
          command: ./gradlew -PreleaseVersion publish

      - deploy:
          name: Close and Release to Maven Central
          command: ./gradlew -PreleaseVersion closeAndReleaseRepository

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud

      - publish-snapshot:
          requires:
            - build
          filters:
            branches:
              only: master

      - publish-release:
          requires:
            - build
          filters:
            branches:
              only: release
