version: 2.1

executors:
  default:
    working_directory: ~/repo/maybe

    docker:
      - image: cimg/base:stable
        environment:
          JVM_OPTS: -Xmx4096m
          TERM: dumb

commands:
  install-jvm:
    description: Install and setup the JVM environmnet

    steps:
      - run:
          name: Get JDK SHA256
          command: |
            mkdir ~/jdk
            wget "https://download.oracle.com/java/18/latest/jdk-18_linux-x64_bin.tar.gz.sha256" -O ~/jdk/jdk-18.sha256

      - restore_cache:
          key: v1-jdk-18-{{ checksum "~/jdk/jdk-18.sha256" }}

      - run:
          name: Download JDK 18.0.1.1
          command: |
            if [ ! -f ~/jdk/jdk-18.tar.gz ]; then
              wget -nc https://download.oracle.com/java/18/latest/jdk-18_linux-x64_bin.tar.gz -O ~/jdk/jdk-18.tar.gz
            fi

      - run:
          name: Install JDK
          command: |
            sudo tar xvf ~/jdk/jdk-18.tar.gz -C ~/jdk/
            sudo mv ~/jdk/jdk-18.0.1.1/ /opt/
            echo 'export JAVA_HOME=/opt/jdk-18.0.1.1' >> $BASH_ENV
            echo 'export PATH=$PATH:$JAVA_HOME/bin' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Check Java version
          command: |
            echo $JAVA_HOME
            java --version

      - save_cache:
          paths:
            - ~/jdk/jdk-18.tar.gz
          key: v1-jdk-18-{{ checksum "~/jdk/jdk-18.sha256" }}

  setup:
    description: "Setup the environment to run tasks on CI"

    steps:
      - checkout:
          path: ~/repo/maybe

      - run:
          name: Provisioning
          command: |
            cp gradle.properties.sample gradle.properties
            sed -i "s/<SIGNING_PASSWORD>/$SIGNING_PASSWORD/g" gradle.properties
            sed -i "s/<NEXUS_USERNAME_TOKEN>/$NEXUS_USERNAME_TOKEN/g" gradle.properties
            sed -i "s/<NEXUS_PASSWORD_TOKEN>/$NEXUS_PASSWORD_TOKEN/g" gradle.properties

      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "buildscript-gradle.lockfile" }}-{{ checksum "gradle.lockfile" }}
            - v4-dependencies-{{ checksum "buildscript-gradle.lockfile" }}-
            - v4-dependencies-

      - run:
          name: Dependencies
          command: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/repo/maybe/.gradle
            - ~/.gradle
          key: v4-dependencies-{{ checksum "buildscript-gradle.lockfile" }}-{{ checksum "gradle.lockfile" }}

jobs:
  build:
    executor: default

    steps:
      - install-jvm

      - setup

      - run:
          name: Compile
          command: ./gradlew compileJava compileTestJava

      - run:
          name: SonarLint
          command: ./gradlew sonarlintMain sonarlintTest

      - run:
          name: Checkstyle
          command: ./gradlew checkstyleMain checkstyleTest

      - run:
          name: Test
          command: ./gradlew test

      - run:
          name: Build
          command:  ./gradlew build

      - run:
          name: Coverage
          command: ./gradlew jacocoTestReport

      - run:
          name: Upload reports
          command: bash <(curl -s https://codecov.io/bash)

  publish-snapshot:
    executor: default

    steps:
      - install-jvm

      - setup

      - run:
          name: Publish to Sonatype Snapshot OSSRH
          command: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository

  publish-release:
    executor: default

    steps:
      - install-jvm

      - setup

      - run:
          name: Publish to Maven Central
          command: ./gradlew -PreleaseVersion publishToSonatype closeAndReleaseSonatypeStagingRepository

workflows:
  main:
    jobs:
      - build

      - publish-snapshot:
          requires:
            - build
          filters:
            branches:
              only: master

      - publish-release:
          requires:
            - build
          filters:
            branches:
              only: release
