version: 2.1

executors:
  default-jvm:
    working_directory: ~/repo/maybe

    docker:
      - image: circleci/openjdk:15-jdk-buster
        environment:
          JVM_OPTS: -Xmx4096m
          TERM: dumb

commands:
  setup:
    description: "Setup the environment to run tasks on CI"

    steps:
      - checkout:
          path: ~/repo/maybe

      - run:
          name: Provisioning
          command: |
            cp gradle.properties.sample gradle.properties
            sed -i "s/<SIGNING_PASSWORD>/$SIGNING_PASSWORD/g" gradle.properties
            sed -i "s/<NEXUS_USERNAME_TOKEN>/$NEXUS_USERNAME_TOKEN/g" gradle.properties
            sed -i "s/<NEXUS_PASSWORD_TOKEN>/$NEXUS_PASSWORD_TOKEN/g" gradle.properties

      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "buildscript-gradle.lockfile" }}-{{ checksum "gradle.lockfile" }}
            - v4-dependencies-{{ checksum "buildscript-gradle.lockfile" }}-
            - v4-dependencies-

  store-cache:
    description: "Store Gradle configuration and dependendies in cache"

    steps:
      - save_cache:
          paths:
            - ~/repo/maybe/.gradle
            - ~/.gradle
          key: v4-dependencies-{{ checksum "buildscript-gradle.lockfile" }}-{{ checksum "gradle.lockfile" }}

jobs:
  build:
    executor: default-jvm

    steps:
      - setup

      - run:
          name: Compile
          command: ./gradlew compileJava compileTestJava
      
      - run:
          name: Lint Gradle
          command: ./gradlew lintGradle

      - run:
          name: SonarLint
          command: ./gradlew sonarlintMain sonarlintTest

      - run:
          name: Checkstyle
          command: ./gradlew checkstyleMain checkstyleTest

      - run:
          name: Test
          command: ./gradlew test

      - run:
          name: Build
          command:  ./gradlew build

      - run:
          name: Coverage
          command: ./gradlew jacocoTestReport

      - store-cache

      - run:
          name: Upload reports
          command: bash <(curl -s https://codecov.io/bash)

      - store_test_results:
          path: build/test-results

  publish-snapshot:
    executor: default-jvm

    steps:
      - setup

      - run:
          name: Publish to Sonatype Snapshot OSSRH
          command: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository

      - store-cache

  publish-release:
    executor: default-jvm

    steps:
      - setup

      - run:
          name: Publish to Maven Central
          command: ./gradlew -PreleaseVersion publishToSonatype closeAndReleaseSonatypeStagingRepository

      - store-cache

workflows:
  main:
    jobs:
      - build

      - publish-snapshot:
          requires:
            - build
          filters:
            branches:
              only: master

      - publish-release:
          requires:
            - build
          filters:
            branches:
              only: release
