---
name: CI

on:
  push:
  workflow_call:

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 20
          check-latest: true
          cache: gradle
      - run: ./gradlew compileJava compileJava17Java compileJava20Java compileTestJava compileJava17TestJava compileJava20TestJava
      - run: ./gradlew checkstyleMain checkstyleJava17 checkstyleJava20 checkstyleTest checkstyleJava17Test checkstyleJava20Test
      - run: ./gradlew sonarlintMain sonarlintJava17 sonarlintJava20 sonarlintTest sonarlintJava17Test sonarlintJava20Test
      - run: ./gradlew test java17Test java20Test
      - run: ./gradlew build
      - run: ./gradlew jacocoTestReport --rerun
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
