---
name: CI

on:
  push:
  workflow_call:

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 20
          check-latest: true
          cache: gradle
      - run: ./gradlew compileJava compileTestJava
      - run: ./gradlew checkstyleMain checkstyleTest
      - run: ./gradlew sonarlintMain sonarlintTest
      - run: ./gradlew test
      - run: ./gradlew build
      - run: ./gradlew jacocoTestReport
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
