name: Auto approve for owner

on:
  check_suite:
    types: [completed]

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - uses: juliangruber/approve-pull-request-action@v1
        if: github.actor == github.repository_owner
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: $GITHUB_REF
