name: Pull Request Build

on:
  pull_request:
    types:
      - opened

jobs:
  trigger-sonar:
    name: Trigger Sonar Cloud Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Provisioning
        run: cp gradle.properties.sample gradle.properties

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.lockfile') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Trigger analysis
        run: ./gradlew build jacocoTestReport sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
